### ISSUE TITLE
program freezes when ftp connection fails

### ISSUE THREAD

**Issue by Photon89** [shutter-project/shutter#113]
replicated several times.  Sorry, i'd look into it, but i don't know any perl.

Launchpad Details: [#LP1192982](https://bugs.launchpad.net/bugs/1192982) Ryan Grissinger - 2013-06-20 14:20:46 +0000

**Comment by jonasstein** [comment]
No freezing in x11-misc/shutter-0.99.4 on Gentoo Linux. I immediately get an error message:
![image](https://user-images.githubusercontent.com/298682/230648658-457ee57e-68c2-48b6-abf8-be72ca0085c7.png)


@Photon89 , could you please test again with the latest version and report if the bug is still there?

**Comment by Photon89** [comment]
I fear, I can't because my username is just being used there because I ran the script which transferred the Launchpad issues to Github. The original reporter can be found here: https://bugs.launchpad.net/shutter/+bug/1192982 But since the bug is 10 years old, I doubt that we can get a report from him. :smiley: 

I'd say, if it works for you, we just close it and are happy to have one less ancient bug report on our list!
