### ISSUE TITLE
Edit window's toolbar with dark system theme is indiscernible 

### ISSUE THREAD

**Issue by paul1149** [shutter-project/shutter#367]
#### Description of requested feature: 
A better toolbar icon set for use with a dark system theme.

#### Reasons for adding feature:
I'm in MX Linux with a KDE desktop with a dark theme, and I didn't even realize there was a toolbar at first, the icons are almost indecipherable. I'm attaching a screenshot.

#### Extra information, such as Shutter version, operating system and ideas for how to implement:
Shutter .96 / 1547

![a_Selection_002](https://user-images.githubusercontent.com/13952246/126035146-74a85669-0090-443a-8e17-262aa53d4cfd.png)

**Comment by Photon89** [comment]
The icons in this toolbar are not Shutter specific but are taken from the icon theme in use. I am surprised that this problem hasn't appeared in other apps as well. Possibly the reason is that Shutter is a GTK app which you use with a KDE desktop. As far as I know, KDE offers the possibility to choose the GTK icon theme (in the Gnome Application Style control panel, as far as I know). Maybe try to change the icon theme there?

**Comment by paul1149** [comment]
Thank you. That makes sense, but I just tried several different desktop themes and icon themes, closing Shutter first then reopening, and see no significant change.

**Comment by Photon89** [comment]
Are you sure that you changed the GTK icons and themes rather than the QT ones?

**Comment by paul1149** [comment]
Ah, perfect. The answer isn't under Icons in KDE, it's at Application Style / GNOME Application Style. There you can spec the gtk 2 and gtk 3 theme and also the cursor and icon themes. I went with "Breeze Dark" for the main themes and the icons, and now it's very clear and attractive.

Thanks for your help!

**Comment by Photon89** [comment]
Great, have fun screenshotting then! :smiley:
