### ISSUE TITLE
shutter in debian 10/11

### ISSUE THREAD

**Issue by hakitcc** [shutter-project/shutter#417]
i would like to know when shutter will be available for installation in recent debian 10//11 ?

**Comment by Photon89** [comment]
It's currently in WNPP, for 50 days, whatever it means: https://www.debian.org/devel/wnpp/being_packaged I guess, I will ask about the current status on the mailing list. :smiley:

**Comment by andrewshadura** [comment]
@hakitcc, since Debian 10 and 11 have already been released, no new software can be added at this point.
However, Shutter is currently [in review](https://ftp-master.debian.org/new/shutter_0.98-1.html) to enter Debian unstable, so it eventually will be eligible for backports to buster and bullseye; on the other hand, buster and bullseye are missing some of its dependencies, so they will have to be backported as well.

**Comment by Photon89** [comment]
Thanks for commenting! Is it possible to update the package to 0.99.2 (latest version) or is 0.98 already frozen for Debian 12?

**Comment by andrewshadura** [comment]
Sure, when the package is accepted, I will update it to the latest version.

**Comment by Photon89** [comment]
Great, thanks!

I think, the question is sufficiently answered, so I'm closing here, but of course further comments are possible.
