### ISSUE TITLE
On Fedora 35, custom selection button is disabled

### ISSUE THREAD

**Issue by stelesgh** [shutter-project/shutter#452]
Hi!
Last week I've reinstalled my laptop with Fedora 35
I'm facing with a problem with Shutter installation because "Selection" button remain disabled and I can't enable it.
How can I fix that?
Thanks in advance
SL

**Comment by Photon89** [comment]
I'm sorry, I read "section" rather than "selection"...

Second attempt: Are you possibly using Wayland? If so, this is expected, the Wayland support is only rudimentary, that is, only allows full screen capture so far: https://github.com/shutter-project/shutter/issues/187 The only workaround to restore the full functionality is to switch to Xorg.

**Comment by stelesgh** [comment]
Ok! Thanks for your feedback!
