### ISSUE TITLE
repology.org | Problems in Wikidata

### ISSUE THREAD

**Issue by Ricky-Tigg** [shutter-project/shutter#473]
Hello. In its current configuration, [Repology](https://repology.org/), an on-line service aimed to be a packaging hub, gets its information associated to packages from a unique source – [Wikidata](https://www.wikidata.org). Thus that very dependency makes it unreliable, as the information it gathers can at best be as in-accurate as the one that is present in that source. As a consequence, are present there package versions having been **assigned wrong label colour codes**.

_legend | label colour codes involved in issue_

![repology org_label_colour_codes](https://user-images.githubusercontent.com/26058215/172784115-ccb46888-2310-4961-8fb8-37b212475e91.png)

The component _shutter_ currently [illustrates](https://repology.org/projects/?search=shutter&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=) that case. Its maintenance takes place at [page](https://www.wikidata.org/wiki/Q18088089). Components whose definitions are erroneous are [reported](https://repology.org/repository/wikidata/problems).

**Comment by Photon89** [comment]
Are you referring to the fact that in some repos an outdated version is marked as legacy?

**Comment by Ricky-Tigg** [comment]
That the issue, reported as "_Homepage link http://shutter-project.org/ is a permanent redirect to its HTTPS counterpart https://shutter-project.org/ and should be updated._", might be the cause of wrong labels assignment.


"

**Comment by Photon89** [comment]
I changed the URL at https://www.wikidata.org/wiki/Q18088089, let's see when repology picks up the change!

**Comment by DarthGandalf** [comment]
FTR, you don't need us to update wikidata :) It being a wiki, anyone can edit it

**Comment by Photon89** [comment]
Looks like repology has picked up the change, as Shutter is not on the error list any more, but this did not affect the version numbers. Actually, the Wikidata entry only contains three version numbers which are all outdated, so I don't think that it is the actual information source where Repology takes its data from...

**Comment by DarthGandalf** [comment]
Can you explain what is the exact issue you think there is? Because repology looks correct to me.

**Comment by DarthGandalf** [comment]
> there package versions having been assigned wrong label colour codes.

Are you saying 0.99.2 is not the latest version, or?

**Comment by Ricky-Tigg** [comment]
"_don't need us to update wikidata_"; you investigated that. I had conceived that one of yours is granted administrator right to edit. At last the ugly; i read ![repology_shutter](https://user-images.githubusercontent.com/26058215/173011727-514fe2c6-5aa1-4e31-b935-e9cd451a4126.png) as _0.99.2_ instead of _0.99_. That's what happen when you do overwork. Don't do that.

**Comment by DarthGandalf** [comment]
Ah, yeah, that number 2 just means that 2 repositories (across various linux distros etc) have version 0.99

Though that number is inconsistent with what I see in https://repology.org/project/shutter/versions - that page lists 4 repos with 0.99, but in yellow color which means the same repos also contain newer versions. Anyway, that's repology issue.

**Comment by Photon89** [comment]
Well, it all looks good, the only thing in question is how the label "legacy" version is to be handled. Some versions are marked as legacy in one distro and outdated in another (say, version 0.93.1 is legacy in Fedora 31 but outdated in Fedora 30). But maybe this is just distro specific thinking which should not be touched by upstream.

**Comment by DarthGandalf** [comment]
Fedora 31 has 2 versions
![Выделение_426](https://user-images.githubusercontent.com/325092/173015015-4a5ed37f-8c6e-43d2-9147-4ee6735469cd.png)

This is why the older of these 2 versions is "legacy"

**Comment by Photon89** [comment]
Ah, I see! Well, then everything is consistent. Though I wonder why some distros keep outdated versions as legacy alongside more recent version. :smiley:

**Comment by DarthGandalf** [comment]
For example, Gentoo does it for 2 main reasons

1. When a new version is added, it's not marked as stable on any architecture yet
![Выделение_427](https://user-images.githubusercontent.com/325092/173016404-4959165a-d7d0-4b73-a4cb-106d8a2fae29.png)

Here, Krita 5.0.2 is marked as stable on amd64, but 5.0.8 is marked as testing (~). And it's testing on several other arches.
After a while, when the package was in testing at least for a month, it can be added to stable on that arch, and if the arches match between 2 versions, the older one can be deleted. 

Normally, the old version is removed as soon as new version is stabilized, but as I don't have direct access to gentoo packages, opening a PR which just removes the old version is too much overhead for not much benefit. I usually bundle such removal with other changes to the package, e.g. adding a new version.

2. If the old version is still available, it's easier to locally revert to it if the new version has some bug. Installing a version not from repo is possible, but more difficult.

There are more complicated cases, when several versions can be installed in parallel:
![Выделение_428](https://user-images.githubusercontent.com/325092/173017979-44d14288-c2ff-4745-90bd-a8ec298813ae.png)

Here you can see that GCC 11 has different architectures marked as stable on the versions which are newer than the oldest available 11, so that version can't be deleted yet. OTOH, 10.3.0-r2 probably can be deleted already.

> Well, then everything is consistent.

Except for the [search page](https://repology.org/projects/?search=shutter&maintainer=&category=&inrepo=&notinrepo=&repos=&families=&repos_newest=&families_newest=) linked at first, which turns legacy versions also red, and shows a different number there. I counted 4 repos with 0.99, not 2.

**Comment by Ricky-Tigg** [comment]
"_number 2 just means that 2 repositories_"; I did know. That is precisely what "_That's what happen when you do overwork._" meant. All numbers had became version numbers!. You don't realise how your comments were useful to me. Bye.

**Comment by Photon89** [comment]
@DarthGandalf I see, thanks for the explanation! In Arch Linux there is the tool "downgrade" which has access to several previous versions of any given package using the so called Arch Linux Archive, but these versions aren't accessible directly through the package management: https://wiki.archlinux.org/title/Arch_Linux_Archive

**Comment by DarthGandalf** [comment]
Actually, yet another reason is that it's possible to depend on some particular version of the dependency. E.g. `>=dev-cpp/foo-2.0` or `<dev-cpp/bar-3.0`, then the package manager will have to satisfy such constraints to select a version for every package
