### ISSUE TITLE
takes a long time to screenshot very very slow

### ISSUE THREAD

**Issue by Chrysanthemum536** [shutter-project/shutter#672]
#### Brief summary of issue
there is a 0.6s delay between pressing printscreen and taking the screnshot

#### Steps to reproduce the issue

1. printscreen keybind to Auto dark mode
2. press printscreen
3. it takes a very long time (0.6s)

**Comment by Chrysanthemum536** [comment]
the capture delay is set to 0 seconds

**Comment by Rezerkity** [comment]
I have the same issue on Linux Mint. Shutter takes approximately 0.5 to 1 seconds delay before taking the screenshot, regardless of how busy the CPU is. All delay options are disabled or set to 0, but it consistently still takes this long to function.

**Comment by Photon89** [comment]
In `Preferences > Behavior > Window preferences` please set `Redraw delay` to 0 and check if this would solve the problem for you.

To elaborate: There is a timeout  (400ms by default) which allows the Shutter main window or any dialog Shutter shows  to hide in time before the screen state is captured. The issue is that this timeout is applied, no matter if there is actually a window or a dialog to be hidden or not. But let's first test if this timeout is what is actually causes the delay for you guys!

**Comment by Photon89** [comment]
I committed a possible fix: https://github.com/shutter-project/shutter/tree/fix-672 

Now the redraw delay is only applied if the main window is visible and needs to be hidden or when the screenshot command is fired from tray menu (because the tray menu needs some milliseconds to be hidden as well). However, if there are some Shutter notifications still shown, they might enter the screenshot. I'm not sure how to reproduce this case so far.

However, there might be a second issue, see https://github.com/shutter-project/shutter/issues/549

**Comment by Rezerkity** [comment]
> In `Preferences > Behavior > Window preferences` please set `Redraw delay` to 0 and check if this would solve the problem for you.
> 
> To elaborate: There is a timeout (400ms by default) which allows the Shutter main window or any dialog Shutter shows to hide in time before the screen state is captured. The issue is that this timeout is applied, no matter if there is actually a window or a dialog to be hidden or not. But let's first test if this timeout is what is actually causes the delay for you guys!

Redraw delay has a minimum value of 100 (it will reset to 100 if you try to go below it), and I've kept it to that minimum value. However, the minimum value doesn't match the actual delay I experience. I did look into trying your committed fix, but I'm not tech savvy enough to understand how to integrate that into my installation - I only started using Linux recently.

**Comment by Photon89** [comment]
Welcome aboard the Linux train! :smiley: 

I checked this and can just confirm what @DarthGandalf has already written in #549, I fear, there is not much we can do about it right now. I'll close this as duplicate, but please feel free to continue the discussion at #549!
